### ISSUE TITLE
v0.3 checklist

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/tendo#66]
- [x] require >=py38 and update metadata
- [x] remove six
- [x] convert readme to markdown
- [ ] activate pylint hook
- [ ] activate mypy hook
